"""Base strategy interface for Trading Quest."""
from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Optional

import pandas as pd


@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    symbol: str
    side: str  # "BUY" or "SELL"
    qty: float = 0.0
    price: Optional[float] = None
    order_type: str = "MARKET"
    confidence: float = 0.0
    reason: str = ""
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None

    def to_dict(self) -> dict:
        return {
            "symbol": self.symbol,
            "side": self.side,
            "qty": self.qty,
            "price": self.price,
            "order_type": self.order_type,
            "confidence": self.confidence,
            "reason": self.reason,
            "stop_loss": self.stop_loss,
            "take_profit": self.take_profit,
        }


class BaseStrategy(ABC):
    """Abstract base for all trading strategies."""

    name: str = "unnamed"
    description: str = ""
    version: str = "1.0"
    timeframes: list[str] = ["1d"]

    @abstractmethod
    def decide(self, data: pd.DataFrame, portfolio: Any) -> list[dict]:
        """Return a list of signal dicts: {symbol, side, qty, ...}.

        Args:
            data: OHLCV DataFrame with DatetimeIndex.
            portfolio: VirtualPortfolio or similar.
        """
        ...

    def on_candle(self, candle: dict, portfolio: Any) -> list[dict]:
        """Process a single candle. Override for candle-by-candle strategies."""
        return []

    def on_candle_mtf(self, candles: dict[str, pd.DataFrame],
                      portfolio: Any) -> list[dict]:
        """Process multi-timeframe candles.

        Args:
            candles: Dict mapping timeframe string to DataFrame.
            portfolio: Portfolio instance.
        """
        # Default: use the first timeframe
        if candles:
            first_tf = next(iter(candles))
            return self.decide(candles[first_tf], portfolio)
        return []

    def on_day_start(self, date: str, portfolio: Any) -> None:
        """Called at the start of each trading day."""
        pass

    def on_day_end(self, date: str, portfolio: Any) -> None:
        """Called at the end of each trading day."""
        pass

    def configure(self, params: dict) -> None:
        """Set tunable parameters."""
        for k, v in params.items():
            setattr(self, k, v)

    def get_params(self) -> dict:
        """Return current parameter values."""
        return {}

    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} name={self.name}>"
